#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-presto
Version  : 0.224
Release  : 1
URL      : https://github.com/prestodb/presto/archive/0.224.tar.gz
Source0  : https://github.com/prestodb/presto/archive/0.224.tar.gz
Source1  : https://repo1.maven.org/maven2/com/facebook/presto/hadoop/hadoop-apache2/2.7.3-1/hadoop-apache2-2.7.3-1.jar
Source2  : https://repo1.maven.org/maven2/com/facebook/presto/hadoop/hadoop-apache2/2.7.3-1/hadoop-apache2-2.7.3-1.pom
Source3  : https://repo1.maven.org/maven2/com/facebook/presto/presto-hive/0.187/presto-hive-0.187.jar
Source4  : https://repo1.maven.org/maven2/com/facebook/presto/presto-hive/0.187/presto-hive-0.187.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause GPL-2.0 MIT
Requires: mvn-presto-data = %{version}-%{release}
Requires: mvn-presto-license = %{version}-%{release}

%description
# Presto [![Build Status](https://travis-ci.org/prestodb/presto.svg?branch=master)](https://travis-ci.org/prestodb/presto)

%package data
Summary: data components for the mvn-presto package.
Group: Data

%description data
data components for the mvn-presto package.


%package license
Summary: license components for the mvn-presto package.
Group: Default

%description license
license components for the mvn-presto package.


%prep
%setup -q -n presto-0.224

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-presto
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-presto/LICENSE
cp presto-jdbc/src/main/resources/META-INF/license/LICENSE.jol.txt %{buildroot}/usr/share/package-licenses/mvn-presto/presto-jdbc_src_main_resources_META-INF_license_LICENSE.jol.txt
cp presto-main/src/main/resources/webapp/vendor/bootstrap/LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-presto/presto-main_src_main_resources_webapp_vendor_bootstrap_LICENSE.txt
cp presto-main/src/main/resources/webapp/vendor/d3/LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-presto/presto-main_src_main_resources_webapp_vendor_d3_LICENSE.txt
cp presto-main/src/main/resources/webapp/vendor/highlightjs/9.3/LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-presto/presto-main_src_main_resources_webapp_vendor_highlightjs_9.3_LICENSE.txt
cp presto-main/src/main/resources/webapp/vendor/vis/dist/LICENSE-MIT.txt %{buildroot}/usr/share/package-licenses/mvn-presto/presto-main_src_main_resources_webapp_vendor_vis_dist_LICENSE-MIT.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/facebook/presto/hadoop/hadoop-apache2/2.7.3-1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/facebook/presto/hadoop/hadoop-apache2/2.7.3-1/hadoop-apache2-2.7.3-1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/facebook/presto/hadoop/hadoop-apache2/2.7.3-1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/facebook/presto/hadoop/hadoop-apache2/2.7.3-1/hadoop-apache2-2.7.3-1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/facebook/presto/presto-hive/0.187
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/facebook/presto/presto-hive/0.187/presto-hive-0.187.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/facebook/presto/presto-hive/0.187
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/com/facebook/presto/presto-hive/0.187/presto-hive-0.187.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/facebook/presto/hadoop/hadoop-apache2/2.7.3-1/hadoop-apache2-2.7.3-1.jar
/usr/share/java/.m2/repository/com/facebook/presto/hadoop/hadoop-apache2/2.7.3-1/hadoop-apache2-2.7.3-1.pom
/usr/share/java/.m2/repository/com/facebook/presto/presto-hive/0.187/presto-hive-0.187.jar
/usr/share/java/.m2/repository/com/facebook/presto/presto-hive/0.187/presto-hive-0.187.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-presto/LICENSE
/usr/share/package-licenses/mvn-presto/presto-jdbc_src_main_resources_META-INF_license_LICENSE.jol.txt
/usr/share/package-licenses/mvn-presto/presto-main_src_main_resources_webapp_vendor_bootstrap_LICENSE.txt
/usr/share/package-licenses/mvn-presto/presto-main_src_main_resources_webapp_vendor_d3_LICENSE.txt
/usr/share/package-licenses/mvn-presto/presto-main_src_main_resources_webapp_vendor_highlightjs_9.3_LICENSE.txt
/usr/share/package-licenses/mvn-presto/presto-main_src_main_resources_webapp_vendor_vis_dist_LICENSE-MIT.txt
